import { Product } from '../types/product'

export const MOCK_PRODUCTS: Product[] = [
  {
    id: 1,
    name: 'Атласна стрічка "Випускник"',
    category: 'ribbon',
    color: 'coral',
    price: 45,
    minOrder: 10,
    popular: true,
    isNew: false,
    description: 'Класична атласна стрічка з індивідуальним написом. Матеріал — поліестер 100%, ширина 10 см.',
    tags: ['випускний', 'атлас', 'іменна'],
  },
  {
    id: 2,
    name: 'Стрічка синьо-жовта "Патріот"',
    category: 'ribbon',
    color: 'blue-yellow',
    price: 50,
    minOrder: 10,
    popular: true,
    isNew: false,
    description: 'Двоколірна стрічка в кольорах прапору з можливістю нанесення будь-якого тексту сріблом або золотом.',
    tags: ['випускний', 'патріотична', 'двоколірна'],
  },
  {
    id: 3,
    name: 'Стрічка "Золотий випускник"',
    category: 'ribbon',
    color: 'gold',
    price: 65,
    minOrder: 5,
    popular: true,
    isNew: false,
    description: 'Преміальна золота стрічка з блискучою вишивкою. Відмінний вибір для нагородження відмінників.',
    tags: ['відмінник', 'золото', 'преміум'],
  },
  {
    id: 4,
    name: 'Стрічка біла "Класика"',
    category: 'ribbon',
    color: 'white',
    price: 40,
    minOrder: 10,
    popular: false,
    isNew: false,
    description: 'Елегантна біла стрічка — вічна класика для шкільних урочистостей. Чорний або кольоровий друк.',
    tags: ['класика', 'біла', 'елегантна'],
  },
  {
    id: 5,
    name: 'Стрічка червона "Переможець"',
    category: 'ribbon',
    color: 'red',
    price: 48,
    minOrder: 10,
    popular: false,
    isNew: true,
    description: 'Яскраво-червона стрічка для переможців олімпіад та конкурсів.',
    tags: ['олімпіада', 'перемога', 'конкурс'],
  },
  {
    id: 6,
    name: 'Стрічка фіолетова "Творчість"',
    category: 'ribbon',
    color: 'purple',
    price: 48,
    minOrder: 10,
    popular: false,
    isNew: true,
    description: 'Нестандартний вибір для творчих заходів, театральних фестивалів та мистецьких конкурсів.',
    tags: ['творчість', 'фестиваль', 'мистецтво'],
  },
  {
    id: 7,
    name: 'Медаль "Випускник року"',
    category: 'medal',
    price: 85,
    minOrder: 1,
    popular: true,
    isNew: false,
    description: 'Металева медаль на стрічці з гравіюванням імені та року. Діаметр 70 мм, колір на вибір.',
    tags: ['медаль', 'нагорода', 'гравіювання'],
  },
  {
    id: 8,
    name: 'Медаль "За відмінне навчання"',
    category: 'medal',
    price: 90,
    minOrder: 1,
    popular: false,
    isNew: false,
    description: 'Класична шкільна медаль із зображенням книги та факела. Золоте або срібне покриття.',
    tags: ['медаль', 'відмінник', 'нагорода'],
  },
  {
    id: 9,
    name: 'Медаль "Переможець олімпіади"',
    category: 'medal',
    price: 95,
    minOrder: 1,
    popular: false,
    isNew: true,
    description: 'Спортивна медаль для олімпіад і змагань. I, II, III місця. Індивідуальна гравіювання.',
    tags: ['олімпіада', 'змагання', 'місце'],
  },
  {
    id: 10,
    name: 'Грамота "Випускник"',
    category: 'certificate',
    price: 25,
    minOrder: 5,
    popular: false,
    isNew: false,
    description: 'Святкова грамота А4 з іменем, класом та датою. Кольоровий друк на дизайнерському папері.',
    tags: ['грамота', 'диплом', 'друк'],
  },
  {
    id: 11,
    name: 'Диплом "З відзнакою"',
    category: 'certificate',
    price: 35,
    minOrder: 1,
    popular: false,
    isNew: false,
    description: 'Преміальний диплом на картоні з тисненням і стрічкою. Формат A4.',
    tags: ['диплом', 'відзнака', 'преміум'],
  },
  {
    id: 12,
    name: 'Набір "Випускний під ключ"',
    category: 'accessory',
    price: 320,
    minOrder: 1,
    popular: true,
    isNew: false,
    description: 'Комплект для класу: стрічки + медаль + грамота для кожного учня. Знижка 15% від окремих цін.',
    tags: ['набір', 'комплект', 'знижка'],
  },
  {
    id: 13,
    name: 'Підвіска "Зірка випускника"',
    category: 'accessory',
    price: 55,
    minOrder: 1,
    popular: false,
    isNew: true,
    description: 'Металева зірка-підвіска із гравіюванням на замовлення. Можна прикріпити до стрічки або рюкзака.',
    tags: ['підвіска', 'зірка', 'декор'],
  },
  {
    id: 14,
    name: 'Стрічка зелена "Еко"',
    category: 'ribbon',
    color: 'green',
    price: 45,
    minOrder: 10,
    popular: false,
    isNew: true,
    description: 'Зелена стрічка з еко-принтом. Підходить для шкільних екологічних заходів та фестивалів.',
    tags: ['еко', 'зелена', 'фестиваль'],
  },
  {
    id: 15,
    name: 'Стрічка чорна "Преміум"',
    category: 'ribbon',
    color: 'black',
    price: 70,
    minOrder: 5,
    popular: false,
    isNew: false,
    description: 'Чорна оксамитова стрічка з золотим написом — для особливих урочистостей і нагороджень.',
    tags: ['чорна', 'оксамит', 'золото'],
  },
]
